global:
  scrape_interval: 15s # How often to grab metrics

scrape_configs:
  # Job to scrape RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  # Job to scrape your Spring Boot App
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-service:8080']