spring.application.name=spring-boot-observability-nexus

# 1. Basic Metadata (Critical for Tracing and Service Maps)
#spring.application.name=observability-nexus-service

# 2. RabbitMQ Connection (Points to the container name in Docker Compose)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 3. Observability: Actuator & Micrometer
# Expose the /actuator/prometheus endpoint
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true

# 4. Metrics & Tracing (Micrometer Tracing/Otel)
management.tracing.sampling.probability=1.0
management.metrics.tags.application=${spring.application.name}