spring.application.name=spring-boot-observability-nexus
# Application Server Port
#server.port=8080
# 1. Basic Metadata (Critical for Tracing and Service Maps)
#spring.application.name=observability-nexus-service

# 2. RabbitMQ Connection (Points to the container name in Docker Compose)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 3. Observability: Actuator & Micrometer
# Expose the /actuator/prometheus endpoint
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true

# 4. Metrics & Tracing (Micrometer Tracing/Otel)
management.tracing.sampling.probability=1.0
management.metrics.tags.application=${spring.application.name}

# 5.Fix the BusBridge Error
spring.cloud.bus.enabled=false

# 6.Disable OTLP to stop the connection refused logs
management.otlp.metrics.export.enabled=false

# 7.Server Port (Since Prometheus is on 9091)
server.port=9090

# 8.Ensure the health endpoint shows details
management.endpoint.health.show-details=always